name: Unit Tests
on: [push]
jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.7.12
          cache: poetry
      - run: mkdir -p /home/runner/.cache/pypoetry/virtualenvs
      - run: make setup.poetry
      - run: poetry run python -m pytest  ./portfolio/tests/unit
